-- Valtivo AI - initial schema
--
-- Design notes:
--  * All identifiers are UUIDs generated by Postgres.
--  * A session belongs to a user OR to a guest token, never to both. The
--    check constraint enforces that so orphaned/ambiguous rows cannot exist.
--  * owner_hash is a salted HMAC used only for rate limiting. Raw IP
--    addresses are never stored.
--  * Deletes cascade downwards from analysis_sessions so removing an analysis
--    truly removes everything derived from it.

create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------------------
-- Enums
-- ---------------------------------------------------------------------------

create type analysis_status as enum (
  'created', 'uploading', 'processing', 'needs_review', 'completed', 'failed'
);

create type review_status as enum (
  'pending', 'confirmed', 'corrected', 'unknown', 'removed'
);

create type condition_estimate as enum (
  'unknown',
  'possibly_near_mint',
  'possibly_lightly_played',
  'visibly_damaged',
  'needs_better_photo'
);

create type condition_basis as enum ('ungraded', 'near_mint_assumed', 'unknown');

create type image_processing_status as enum (
  'pending', 'processing', 'processed', 'failed', 'needs_manual_review'
);

-- ---------------------------------------------------------------------------
-- profiles
-- ---------------------------------------------------------------------------

create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  display_name text,
  locale text not null default 'nl',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- analysis_sessions
-- ---------------------------------------------------------------------------

create table public.analysis_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users (id) on delete cascade,
  guest_token text,
  owner_hash text,
  status analysis_status not null default 'created',
  status_detail text,
  total_images integer not null default 0,
  detected_cards_count integer not null default 0,
  confirmed_cards_count integer not null default 0,
  unknown_cards_count integer not null default 0,
  error_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz,
  expires_at timestamptz,
  constraint analysis_sessions_owner_check check (
    (user_id is not null and guest_token is null)
    or (user_id is null and guest_token is not null)
  ),
  constraint analysis_sessions_guest_expiry_check check (
    user_id is not null or expires_at is not null
  )
);

create index analysis_sessions_user_id_created_at_idx
  on public.analysis_sessions (user_id, created_at desc);
create index analysis_sessions_owner_hash_created_at_idx
  on public.analysis_sessions (owner_hash, created_at desc);
create unique index analysis_sessions_guest_token_idx
  on public.analysis_sessions (guest_token, id)
  where guest_token is not null;
create index analysis_sessions_expires_at_idx
  on public.analysis_sessions (expires_at)
  where expires_at is not null;

-- ---------------------------------------------------------------------------
-- analysis_images
-- ---------------------------------------------------------------------------

create table public.analysis_images (
  id uuid primary key default gen_random_uuid(),
  analysis_session_id uuid not null
    references public.analysis_sessions (id) on delete cascade,
  storage_path text not null,
  original_filename text not null,
  mime_type text not null,
  width integer not null default 0,
  height integer not null default 0,
  byte_size integer not null default 0,
  processing_status image_processing_status not null default 'pending',
  quality_score numeric(4, 3),
  quality_warnings jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  constraint analysis_images_mime_check
    check (mime_type in ('image/jpeg', 'image/png', 'image/webp'))
);

create index analysis_images_session_idx
  on public.analysis_images (analysis_session_id, created_at);

-- ---------------------------------------------------------------------------
-- catalog_cards (shared, read-only reference data)
-- ---------------------------------------------------------------------------

create table public.catalog_cards (
  id text primary key,
  external_id text not null,
  name text not null,
  set_id text not null,
  set_name text not null,
  set_code text not null default '',
  card_number text not null default '',
  rarity text,
  variant text,
  language text not null default 'en',
  image_small_url text,
  image_large_url text,
  release_date date,
  pokedex_number integer,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index catalog_cards_name_idx on public.catalog_cards (lower(name));
create index catalog_cards_number_idx on public.catalog_cards (card_number);
create index catalog_cards_set_idx on public.catalog_cards (set_code, card_number);
create index catalog_cards_pokedex_idx on public.catalog_cards (pokedex_number);

-- ---------------------------------------------------------------------------
-- detected_cards
-- ---------------------------------------------------------------------------

create table public.detected_cards (
  id uuid primary key default gen_random_uuid(),
  analysis_session_id uuid not null
    references public.analysis_sessions (id) on delete cascade,
  analysis_image_id uuid not null
    references public.analysis_images (id) on delete cascade,
  -- Stable display order. Rows inserted in one batch share created_at and
  -- carry random UUIDs, so an explicit ordinal is what keeps the review list
  -- in a predictable order.
  position integer not null default 0,
  crop_storage_path text,
  region jsonb not null,
  visible_name text,
  visible_card_number text,
  detected_language text,
  variant_hints jsonb not null default '[]'::jsonb,
  recognition_confidence numeric(4, 3),
  selected_catalog_card_id text references public.catalog_cards (id) on delete set null,
  review_status review_status not null default 'pending',
  user_confirmed boolean not null default false,
  condition_estimate condition_estimate not null default 'unknown',
  quantity integer not null default 1 check (quantity between 1 and 99),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint detected_cards_confidence_range
    check (recognition_confidence is null
           or (recognition_confidence >= 0 and recognition_confidence <= 1))
);

create index detected_cards_session_idx
  on public.detected_cards (analysis_session_id, position, id);
create index detected_cards_image_idx on public.detected_cards (analysis_image_id);

-- ---------------------------------------------------------------------------
-- card_match_candidates
-- ---------------------------------------------------------------------------

create table public.card_match_candidates (
  id uuid primary key default gen_random_uuid(),
  detected_card_id uuid not null
    references public.detected_cards (id) on delete cascade,
  catalog_card_id text not null
    references public.catalog_cards (id) on delete cascade,
  match_score numeric(4, 3) not null,
  match_reasons jsonb not null default '[]'::jsonb,
  rank integer not null,
  created_at timestamptz not null default now(),
  unique (detected_card_id, catalog_card_id)
);

create index card_match_candidates_card_rank_idx
  on public.card_match_candidates (detected_card_id, rank);

-- ---------------------------------------------------------------------------
-- price_estimates
-- ---------------------------------------------------------------------------

create table public.price_estimates (
  id uuid primary key default gen_random_uuid(),
  detected_card_id uuid not null
    references public.detected_cards (id) on delete cascade,
  catalog_card_id text references public.catalog_cards (id) on delete set null,
  currency text not null default 'EUR',
  low_value numeric(12, 2),
  mid_value numeric(12, 2),
  high_value numeric(12, 2),
  sample_size integer not null default 0,
  source_name text not null,
  source_url text,
  source_updated_at timestamptz not null default now(),
  condition_basis condition_basis not null default 'ungraded',
  confidence numeric(4, 3) not null default 0,
  warnings jsonb not null default '[]'::jsonb,
  raw_metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  -- A band must be internally consistent; nulls stay allowed on purpose so
  -- "no data" is never coerced into 0.
  constraint price_estimates_band_order check (
    low_value is null or high_value is null or low_value <= high_value
  )
);

create index price_estimates_detected_card_idx
  on public.price_estimates (detected_card_id);

-- ---------------------------------------------------------------------------
-- collection_items
-- ---------------------------------------------------------------------------

create table public.collection_items (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  catalog_card_id text not null references public.catalog_cards (id) on delete cascade,
  quantity integer not null default 1 check (quantity between 1 and 9999),
  condition_estimate condition_estimate not null default 'unknown',
  source_analysis_session_id uuid
    references public.analysis_sessions (id) on delete set null,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, catalog_card_id, condition_estimate)
);

create index collection_items_user_idx
  on public.collection_items (user_id, created_at desc);

-- ---------------------------------------------------------------------------
-- audit_events
-- ---------------------------------------------------------------------------

create table public.audit_events (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users (id) on delete set null,
  analysis_session_id uuid
    references public.analysis_sessions (id) on delete set null,
  event_type text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index audit_events_user_idx on public.audit_events (user_id, created_at desc);
create index audit_events_session_idx on public.audit_events (analysis_session_id);
